# Generated by Django 5.2 on 2026-08-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_link_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
