# Generated by Django 5.2 on 2026-08-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_razorpay_payment_link_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_link_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
