# Generated by Django 5.2 on 2026-08-06 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('order', '0004_order_status_returnrequest_refund'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NDRRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('reason', models.CharField(choices=[('customer_unreachable', 'Customer unreachable'), ('wrong_address', 'Wrong address'), ('refused_delivery', 'Delivery refused'), ('address_incomplete', 'Address incomplete'), ('pincode_mismatch', 'PIN code mismatch'), ('other', 'Other')], default='other', max_length=30)),
                ('courier_remarks', models.TextField(blank=True, help_text='Raw remarks from the courier, if any.')),
                ('reattempt_requested', models.BooleanField(default=False)),
                ('reattempt_at', models.DateTimeField(blank=True, null=True)),
                ('corrected_address', models.TextField(blank=True)),
                ('corrected_phone', models.CharField(blank=True, max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndr_records', to='logistics.shipment')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReturnShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('return_type', models.CharField(choices=[('refund', 'Refund'), ('exchange', 'Exchange')], default='refund', max_length=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pickup_scheduled', 'Pickup Scheduled'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('at_warehouse', 'At Warehouse'), ('inspecting', 'Inspecting'), ('restocked', 'Restocked'), ('refunded', 'Refunded'), ('replaced', 'Replaced'), ('cancelled', 'Cancelled'), ('lost', 'Lost'), ('damaged', 'Damaged')], db_index=True, default='requested', max_length=20)),
                ('reason', models.CharField(blank=True, choices=[('customer_unreachable', 'Customer unreachable'), ('wrong_address', 'Wrong address'), ('refused_delivery', 'Delivery refused'), ('address_incomplete', 'Address incomplete'), ('pincode_mismatch', 'PIN code mismatch'), ('other', 'Other')], default='other', max_length=30)),
                ('customer_notes', models.TextField(blank=True)),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('pickup_address', models.TextField(blank=True)),
                ('pickup_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_reference', models.CharField(blank=True, max_length=100)),
                ('inspection_decision', models.CharField(blank=True, choices=[('ok', 'In good condition'), ('damaged', 'Damaged'), ('used', 'Used / not in original state'), ('wrong_item', 'Wrong item returned'), ('missing_parts', 'Missing parts / accessories'), ('other', 'Other')], max_length=20)),
                ('inspection_notes', models.TextField(blank=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('restocked_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.couriercompany')),
                ('exchange_shipment', models.ForeignKey(blank=True, help_text='New forward shipment created for an exchange.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_exchange', to='logistics.shipment')),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_returns', to='order.order')),
                ('original_shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_shipments', to='logistics.shipment')),
                ('restock_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.warehouse')),
                ('return_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_return_shipments', to='order.returnrequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
