# Generated by Django 5.2 on 2026-08-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_ndrrecord_returnshipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='extra_config',
            field=models.JSONField(blank=True, default=dict, help_text='Ops metadata, e.g. {"performance_score": 94}'),
        ),
    ]
