# Generated by Django 5.2 on 2026-08-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_warehouse_extra_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingevent',
            name='pod_url',
            field=models.URLField(blank=True, help_text='Delivery proof image/URL (POD), when provided by the courier'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='received_by',
            field=models.CharField(blank=True, help_text='Recipient name recorded on the delivery proof', max_length=100),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='source',
            field=models.CharField(choices=[('webhook', 'Courier webhook'), ('poll', 'Courier poll'), ('manual', 'Manual override'), ('system', 'System')], db_index=True, default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 of the raw request body — used to reject courier replays', max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('courier', 'dedupe_key'), name='uniq_webhookevent_courier_dedupe'),
        ),
    ]
