# Generated by Django 5.2 on 2026-08-07 23:48

import core.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_trackingevent_pod_url_trackingevent_received_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couriercompany',
            name='api_key',
            field=core.encrypted_fields.EncryptedCharField(blank=True, help_text='Encrypted at rest.', max_length=512),
        ),
        migrations.AlterField(
            model_name='couriercompany',
            name='api_secret',
            field=core.encrypted_fields.EncryptedCharField(blank=True, help_text='Encrypted at rest.', max_length=512),
        ),
    ]
