# Generated by Django 5.2 on 2026-08-09 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, help_text='Handler key, e.g. "send_email", "fulfil_order", "refund_payment".', max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('dead', 'Dead')], db_index=True, default='pending', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of times the worker has claimed this job.')),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Giving up: attempts >= max_attempts moves the job to dead.')),
                ('run_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Earliest time this job may run.')),
                ('next_run_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the worker should pick this up next (drives retry backoff).')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Lease held by a worker; another worker may reclaim the job after this.', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, help_text='Optional idempotency key: an identical in-flight job is not queued twice.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('next_run_at', 'id'),
                'indexes': [models.Index(fields=['status', 'next_run_at'], name='jobs_job_status_a23a12_idx')],
            },
        ),
    ]
