# Generated by Django 5.2 on 2026-08-01 02:22

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('kind', models.CharField(choices=[('announcement', 'Announcement'), ('news', 'News'), ('event', 'Event')], db_index=True, default='announcement', max_length=16)),
                ('body', ckeditor.fields.RichTextField()),
                ('excerpt', models.CharField(blank=True, help_text='Short teaser shown in the ticker. Leave empty to auto-generate.', max_length=240)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned items scroll first.')),
                ('publish_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional: hide this item automatically after this time.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News item',
                'verbose_name_plural': 'News items',
                'ordering': ('-is_pinned', '-publish_at'),
            },
        ),
    ]
