# Generated by Django 5.2 on 2026-08-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Master switch for the whole Loader Experience System.')),
                ('initial_type', models.CharField(choices=[('seed', 'Seed Grow — brand intro'), ('logo', 'Logo Reveal'), ('spinner', 'Minimal Spinner'), ('progress', 'Progress Bar'), ('none', 'No initial loader')], default='seed', help_text='The animation shown while the first page of a visit loads.', max_length=20)),
                ('navigation_type', models.CharField(choices=[('progress', 'Slim Progress Bar'), ('logo', 'Mini Logo'), ('none', 'No navigation loader')], default='progress', help_text='Small, unobtrusive loader shown while navigating between pages.', max_length=20)),
                ('logo_image', models.ImageField(blank=True, help_text='Optional custom logo. Leave empty to use the brand mark + site name.', null=True, upload_to='loader/')),
                ('logo_text', models.CharField(blank=True, default='', help_text='Text under the logo. Leave empty to use the site name.', max_length=60)),
                ('background_color', models.CharField(default='#0c1017', help_text='Background colour of the loader screen.', max_length=9)),
                ('accent_color', models.CharField(default='#ff7a2f', help_text='Accent colour used by the animation and progress bar.', max_length=9)),
                ('duration_ms', models.PositiveIntegerField(default=1600, help_text='Target duration in milliseconds (400–6000). The loader can finish early when the page is ready.')),
                ('exit_animation', models.CharField(choices=[('fade', 'Fade out'), ('zoom', 'Zoom out'), ('slide', 'Slide up'), ('none', 'Instant')], default='fade', help_text='How the loader leaves the screen.', max_length=20)),
                ('show_on', models.CharField(choices=[('first_visit', 'First visit only'), ('every_visit', 'Every page load'), ('once_per_session', 'Once per session')], default='first_visit', help_text='When the initial loader plays. The large intro is not replayed on every page by default.', max_length=20)),
                ('device_desktop', models.BooleanField(default=True, help_text='Show loaders on desktop.')),
                ('device_tablet', models.BooleanField(default=True, help_text='Show loaders on tablets.')),
                ('device_mobile', models.BooleanField(default=True, help_text='Show loaders on phones.')),
                ('lightweight_mobile', models.BooleanField(default=True, help_text='Use the lightweight spinner on phones instead of the full animation.')),
                ('respect_reduced_motion', models.BooleanField(default=True, help_text='Skip the animation for visitors who prefer reduced motion.')),
                ('network_fallback', models.BooleanField(default=True, help_text='Use the lightweight spinner on slow / data-saving connections.')),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loader Configuration',
                'verbose_name_plural': 'Loader Configuration',
            },
        ),
    ]
