# Generated by Django 5.2 on 2026-08-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaderconfig',
            name='skeleton_enabled',
            field=models.BooleanField(default=True, help_text='After the intro, show a page skeleton while content loads — makes the site feel faster.'),
        ),
        migrations.AlterField(
            model_name='loaderconfig',
            name='initial_type',
            field=models.CharField(choices=[('seed', 'Seed Grow — brand intro'), ('logo', 'Logo Reveal'), ('spinner', 'Minimal Spinner'), ('progress', 'Progress Bar'), ('skeleton', 'Skeleton Screen — page preview'), ('none', 'No initial loader')], default='seed', help_text='The animation shown while the first page of a visit loads.', max_length=20),
        ),
    ]
