# Generated by Django 5.2 on 2026-08-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0002_loaderconfig_skeleton_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaderconfig',
            name='skeleton_pages',
            field=models.JSONField(blank=True, default=dict, help_text='Per-page skeleton toggles. Keys are page types, values enable/disable.'),
        ),
    ]
