# Generated by Django 5.2 on 2026-08-07 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_set_existing_profiles_approved'),
        ('coupons', '0001_initial'),
        ('order', '0009_order_checkout_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Optional whitelist of customers allowed to use this coupon. Empty = everyone.', related_name='allowed_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional cap on the rupee value of the discount.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of times this coupon may ever be used. Leave blank for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart total (before discount) required to use this coupon.', max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='per_user_limit',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of orders one customer can apply this coupon to.'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='seller',
            field=models.ForeignKey(blank=True, help_text="Restrict this coupon to carts that contain this seller's products.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='accounts.sellerprofile'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='coupons.coupon')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-redeemed_at',),
                'constraints': [models.UniqueConstraint(fields=('coupon', 'order'), name='unique_coupon_redemption_per_order')],
            },
        ),
    ]
