# Generated by Django 5.2 on 2026-07-31 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_badge_comment_edited_comment_mentions_comment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.CharField(blank=True, help_text='Paste a YouTube or Vimeo link, or a direct .mp4/.webm file URL.', max_length=500),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/%Y/%m/%d')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='blogs.post')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
