# Generated by Django 5.2 on 2026-08-10 17:23

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_post_video_url_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='blog/%Y/%m/%d', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='blog/authors/%Y/%m/%d', validators=[core.validators.validate_image_file]),
        ),
    ]
