# Generated by Django 5.2 on 2026-08-07 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sellerprofile_account_holder_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Admin feedback shown to the seller when a submission is rejected.'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who last reviewed this seller.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_reviews_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='verification_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='verification_status',
            field=models.CharField(choices=[('unsubmitted', 'Not submitted for review'), ('pending', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='unsubmitted', help_text='Workflow state of the seller verification review.', max_length=12),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='SellerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('gst_certificate', 'GST certificate'), ('business_proof', 'Business registration proof'), ('id_proof', 'Owner ID proof'), ('bank_proof', 'Bank account proof'), ('address_proof', 'Business address proof'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='seller_documents/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.sellerprofile')),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
