# Generated by Django 5.2 on 2026-08-09 12:52

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_set_existing_profiles_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Platform commission for this seller (e.g. 0.10 = 10%). Leave empty to use the marketplace default.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='customer_profiles/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='sellerdocument',
            name='file',
            field=models.FileField(upload_to='seller_documents/', validators=[core.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='seller_profiles/', validators=[core.validators.validate_image_file]),
        ),
    ]
