# Generated by Django 5.2 on 2026-08-01 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'हिन्दी'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch')], default='en', max_length=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('font_style', models.CharField(choices=[('default', 'Default'), ('serif', 'Serif'), ('mono', 'Monospace'), ('rounded', 'Rounded')], default='default', max_length=10)),
                ('accent', models.CharField(choices=[('orange', 'Orange'), ('teal', 'Teal'), ('blue', 'Blue'), ('purple', 'Purple'), ('green', 'Green'), ('rose', 'Rose')], default='orange', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
