# Generated by Django 5.2 on 2026-08-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_userpreference_text_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='accent',
            field=models.CharField(choices=[('orange', 'Orange'), ('teal', 'Teal'), ('blue', 'Blue'), ('purple', 'Purple'), ('green', 'Green'), ('rose', 'Rose'), ('indigo', 'Indigo'), ('cyan', 'Cyan'), ('amber', 'Amber'), ('pink', 'Pink'), ('lime', 'Lime'), ('gold', 'Gold')], default='orange', max_length=10),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='font_style',
            field=models.CharField(choices=[('default', 'Default'), ('serif', 'Serif'), ('mono', 'Monospace'), ('rounded', 'Rounded'), ('elegant', 'Elegant'), ('playful', 'Playful'), ('hand', 'Handwritten')], default='default', max_length=10),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'हिन्दी'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch'), ('pt', 'Português'), ('it', 'Italiano'), ('ja', '日本語'), ('ko', '한국어'), ('zh-hans', '简体中文'), ('ar', 'العربية'), ('ru', 'Русский'), ('tr', 'Türkçe'), ('nl', 'Nederlands'), ('pl', 'Polski'), ('bn', 'বাংলা'), ('ta', 'தமிழ்'), ('te', 'తెలుగు'), ('mr', 'मराठी')], default='en', max_length=10),
        ),
    ]
