# Generated by Django 5.2 on 2026-08-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_alter_userpreference_accent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
