# Generated by Django 5.2 on 2026-08-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('value', models.TextField(blank=True, default='')),
                ('group', models.CharField(db_index=True, max_length=50)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text area'), ('boolean', 'Boolean'), ('select', 'Select'), ('color', 'Color'), ('number', 'Number')], default='text', max_length=20)),
                ('help_text', models.TextField(blank=True, default='')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'ordering': ['group', 'ordering', 'key'],
            },
        ),
    ]
