# Generated by Django 5.2 on 2026-08-08 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_merge_legacy_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
