# Generated by Django 5.2 on 2026-08-09 12:52

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_pending_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='image',
            field=models.ImageField(blank=True, upload_to='reviews/%Y/%m/%d', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='productreviewimage',
            name='image',
            field=models.ImageField(upload_to='reviews/%Y/%m/%d', validators=[core.validators.validate_image_file]),
        ),
    ]
