# Generated by Django 5.2 on 2026-08-01 10:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_variantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Optional. Own description for this variant.'),
        ),
    ]
