# Generated by Django 5.2 on 2026-08-10 17:23

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/variants', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d/variants', validators=[core.validators.validate_image_file]),
        ),
    ]
