# Generated by Django 4.2.30 on 2026-09-28 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEnhancementJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('original', models.FileField(upload_to='ai-enhancements/originals/%Y/%m/%d')),
                ('enhanced', models.FileField(blank=True, upload_to='ai-enhancements/enhanced/%Y/%m/%d')),
                ('background', models.CharField(choices=[('white', 'white'), ('neutral', 'neutral'), ('transparent', 'transparent'), ('original', 'original')], default='white', max_length=16)),
                ('selection', models.CharField(choices=[('none', 'No choice yet'), ('original', 'Keep the original'), ('enhanced', 'Use the enhanced image')], default='none', max_length=16)),
                ('stages', models.JSONField(blank=True, default=list)),
                ('quality', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('is_ai', models.BooleanField(default=False)),
                ('advisor_notes', models.CharField(blank=True, max_length=240)),
                ('error_code', models.CharField(blank=True, max_length=48)),
                ('error_message', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_enhancement_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['seller', '-created_at'], name='ai_services_seller__41a92e_idx')],
            },
        ),
    ]
