# Generated by Django 5.2 on 2026-08-08 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
