# Generated by Django 5.2 on 2026-08-01 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_enabled', models.BooleanField(default=True, verbose_name='Order updates')),
                ('payment_enabled', models.BooleanField(default=True, verbose_name='Payment updates')),
                ('shipping_enabled', models.BooleanField(default=True, verbose_name='Shipping updates')),
                ('deal_enabled', models.BooleanField(default=True, verbose_name='Deals & promotions')),
                ('review_enabled', models.BooleanField(default=True, verbose_name='Reviews & ratings')),
                ('account_enabled', models.BooleanField(default=True, verbose_name='Account security')),
                ('system_enabled', models.BooleanField(default=True, verbose_name='System & service')),
                ('promo_enabled', models.BooleanField(default=True, verbose_name='Marketing offers')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='Email summary')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller'), ('admin', 'Admin')], default='customer', help_text='Audience this notification is meant for.', max_length=20)),
                ('category', models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('shipping', 'Shipping'), ('deal', 'Deals & Promotions'), ('review', 'Reviews'), ('account', 'Account'), ('system', 'System'), ('promo', 'Marketing')], default='system', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon, e.g. "box"', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='Target user. Leave empty to broadcast to a whole role.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_86ea8b_idx')],
            },
        ),
    ]
