# Generated by Django 5.2 on 2026-08-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='emailed_at',
            field=models.DateTimeField(blank=True, help_text='When this notification was included in an email digest.', null=True),
        ),
    ]
