# Generated by Django 5.2 on 2026-08-06 19:04

from django.db import migrations, models
from django.utils import timezone


def backfill_order_numbers(apps, schema_editor):
    Order = apps.get_model('order', 'Order')
    year = timezone.localdate().year
    for order in Order.objects.filter(order_number='').order_by('id'):
        order.order_number = 'SEED-{}-{:06d}'.format(year, order.id)
        order.save(update_fields=['order_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_phone_order_state_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Human-friendly public order reference.', max_length=30),
        ),
        migrations.RunPython(backfill_order_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Human-friendly public order reference.', max_length=30, unique=True),
        ),
    ]
