# Generated by Django 5.2 on 2026-08-07 01:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_coupon_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.18'), help_text='Tax rate applied to this order (e.g. 0.18 = 18% GST).', max_digits=4),
        ),
    ]
