# Generated by Django 5.2 on 2026-08-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_token',
            field=models.CharField(blank=True, db_index=True, help_text='Idempotency key that prevents duplicate order creation on resubmission.', max_length=64, null=True, unique=True),
        ),
    ]
